services:
  database:
    image: mysql:8.0
    container_name: mysql_docker
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: equadis
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./src/main/docker:/docker-entrypoint-initdb.d

  app:
    build:
      context: .
    container_name: spring_app
    ports:
      - "8080:8080"
    depends_on:
        - database
    environment:
        MYSQL_HOST: localhost
        MYSQL_PORT: 3306
        MYSQL_DATABASE: equadis
        MYSQL_USER: root
        MYSQL_PASSWORD: 123456

volumes:
  db_data:

